---
# tasks file for basic
- name: 1. Check OS Distribution Ubuntu
  debug:
    msg: "{{ ubuntu }}"
  with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
  loop_control:
    loop_var: ubuntu
  tags:
    - check_os_distribution

- name: 2. Install system updates for ubuntu systems
  apt:
    name: '*'
    state: latest
    update_cache: yes
    #cache_valid_time: 3600
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution == "Ubuntu"

- name: 3. Install minimal system
  apt:
    pkg:
      - nano
      - net-tools
      - build-essential
      - iputils-ping
    state: latest
    update_cache: true

- name: 4. Reboot system
  reboot:
    post_reboot_delay: 30
    test_command: uptime